version: '3'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "443:443"
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000